name: Build

on:
  push:
    paths-ignore:
      - bruno/**
      - .run/**

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew clean build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:latest"

      - name: Create staging
        if: github.ref == 'refs/heads/main'
        run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:staging ${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:latest

      - name: Generate summary
        run: |
          echo "Tag: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
