name: Build

on:
  push:
    paths:
      - frontend/**

jobs:
  push:
    name: "Build search frontend"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/jzfrontend:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/jzfrontend:latest"

      - name: Create staging
        if: github.ref == 'refs/heads/main'
        run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/jzfrontend:staging ${{ secrets.DOCKERHUB_USERNAME }}/jzfrontend:latest

      - name: Generate summary
        run: |
          echo "Tag: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
