name: Release

on:
  push:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create release
        run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:release ${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:staging

      - name: Create tag
        run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:${{ github.ref_name }} ${{ secrets.DOCKERHUB_USERNAME }}/jzhistory:staging
