name: Backend

on:
  push:
    paths:
      - search/**

jobs:
  push:
    name: "Build search backend"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew :search:clean :search:build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./search
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/jzsearch:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/jzsearch:latest"

      - name: Create staging
        if: github.ref == 'refs/heads/main'
        run: docker buildx imagetools create -t ${{ secrets.DOCKERHUB_USERNAME }}/jzsearch:staging ${{ secrets.DOCKERHUB_USERNAME }}/jzsearch:latest

      - name: Generate summary
        run: |
          echo "Tag: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload reports if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: search-reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload coverage if passed
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: search-coverage
          path: |
            **/build/reports/jacoco/